#!/bin/bash

declare -a pkgs

if [ $EUID -ne 0 ]; then
  ROOT="sudo"
fi

$ROOT apt-get update

while (( $# )); do
  case $1 in
    --pkgs=*) pkgs+=( "${1#*=}" );;
    *) ;;
  esac
  shift
done


$ROOT apt-get upgrade -y
$ROOT apt-get dist-upgrade -y
$ROOT apt-get install "${pkgs[@]}"
$ROOT apt-get autoremove -y
$ROOT apt-get autoclean -y
