#!/bin/bash

declare -a pkgs casks

# Check for Homebrew existence
which -s brew
if [[ $? != 0 ]];
then  
  # Install Homebrew 
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  brew upgrade
  brew update
fi


while (( $# )); do
  case $1 in
    --pkgs=*) pkgs+=( "${1#*=}" );;
    --casks=*) casks+=( "${1#*=}" );;
  esac
  shift
done


# Install packages
brew install "${pkgs[@]}" 

# Install casks
brew tap caskroom/cask
brew cask install "${casks[@]}"

# Remove outdated formulae from the cellar
brew cleanup

exit $?

