#! /bin/bash

echo "    **************************************"
echo "  ****   Proca-dotfiles: Installation   ****"
echo "**********************************************"

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONF_FILES="runcom"

echo "[INFO]  Creating symlinks in home directory for *rc files..."
for CONF in $CONF_FILES; do
  for DOTFILE in `find $DOTFILES_DIR/$CONF -type f`; do
    
    FILE_NAME=`basename $DOTFILE`
    
    # Create backups
    if [ -f ~/$FILE_NAME ]; then
      echo "[INFO]  Creating backup for existing $FILE_NAME file..."
      cat ~/$FILE_NAME > ~/$FILE_NAME.bak
    fi

    # Create symlink 
    if [ ! -L "$DOTFILE" ]; then
      ln -sfv "$DOTFILE" ~
    fi

  done
done

if [ ! -L "$DOTFILES_DIR" ]; then
  echo "[INFO] Symlinking the dotfiles directory from home directory..."
  ln -sfv "$DOTFILES_DIR" ~
fi

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  echo "Shall I install vim-plug for plugin management? [y/n] "
  read res
  if [ "$res" == "y" ]; then 
    echo "[INFO]  Installing vim-plug for plugin management."
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim +PlugInstall +:qa
  fi
else
  vim +PlugInstall +:qa
  vim +PlugUpgrade +:qa
  vim +PlugClean! +:qa
fi

echo "[INFO] Enabling new configuration..."
source ~/.bashrc

# External packages ###########################################################

EXT_PKGS=modules

echo "Shall I proceed installing external packages via your package manager? [y/n]"
read res
if [ "$res" == "y" ]; then

  if [ $(uname) == "Darwin" ];
  then 
    INSTALLER=$EXT_PKGS/brewit
  else 
    INSTALLER=$EXT_PKGS/aptit
  fi
  
  source $DOTFILES_DIR/$EXT_PKGS/.module_list  

  $INSTALLER "${packages[@]/#/--pkgs=}" "${casks[@]/#/--casks=}"
fi


echo "[INFO]  All done."

exit $?
