#! /bin/bash

echo "    **************************************"
echo "  ****   Proca .vimrc: Installation   ******"
echo "**********************************************"

if [ ! -f ~/.vim/autoload/pathogen.vim ]; then 
	echo "[INFO] Downloading vim pathogen (package manager)..."
	mkdir -p ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

if [ ! -d ~/.vim/bundle/nerdtree ]; then
	echo "[INFO] Downloading NERDTree..."
	git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
fi

COMMENTER=""
if [ ! -d ~/.vim/bundle/nerdcommenter ]; then
	echo "[INFO] Downloading NERDCommenter..."
	git clone https://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter
fi 

if [ -f ~/.vimrc ]; then
  echo "[INFO]  Creating backup for existing .vimrc file..."
  mv ~/.vimrc ~/.vimrc.bak
fi

echo "[INFO]  Setting proca_vimrc as default .vimrc file..."
cp .vimrc ~/.vimrc

echo "  Done."

exit $?

